controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        de: ''
        en: '/en'
    requirements:
        prefix: '%locales%'
